### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by hsluoyz** [casbin/tikv-watcher#3]
Like: https://github.com/casbin/redis-watcher#redis-watcher

![image](https://user-images.githubusercontent.com/3787410/126053617-c03fa557-37b6-4257-802b-2a8c54dfcb68.png)

Also there are some typos and miscaptitalisum, it should be TiKV instead of tikv.

![image](https://user-images.githubusercontent.com/3787410/126053629-b13e1d22-e14d-4823-8640-e9e175ec576d.png)

**Comment by hsluoyz** [comment]
@ComradeProgrammer

**Comment by ComradeProgrammer** [comment]
I shall fix it very soon

**Comment by hsluoyz** [comment]
@ComradeProgrammer also the hyperlink, see: https://github.com/casbin/redis-watcher

![image](https://user-images.githubusercontent.com/3787410/126058627-119ba812-e0bf-4db8-ae84-2d5dbec32241.png)
